apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chronomuscu-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: chronomuscu.ingress.local
    http:
      paths:
      - backend:
          service:
            name: chronomuscu-ui-svc
            port:
              number: 4200
        path: /
        pathType: Prefix
