apiVersion: v1
kind: Service
metadata:
  labels:
    app: chronomuscu-ui
  name: chronomuscu-ui-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "serve"
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: chronomuscu
    container: ui
  type: ClusterIP